version: 0.0
os: linux
files:
  - source: ./hello.py
    destination: /home/ec2-home/

hooks:
  BeforeInstall:
    - location: codedeploy/install_server.sh
      timeout: 30
  ApplicationStop:
    - location: codedeploy/stop_server.sh
      timeout: 30
  ApplicationStart:
    - location: codedeploy/start_server.sh
      timeout: 30
